services:
  - type: web
    name: serif-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: serif-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: serif-db
    databaseName: serif
    user: serif_user
